# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3302c3de9b8b39f92460b6a99c6690abb00ac2a75540920b52378ebf19a31cf3971e2cf339383dec937b399e28e656b213629413f6c4c82866673531d305660f

test:
  secret_key_base: 394d8d5ad9f8647836ebdf0358c65fa299f0729bf1e25ae6f7d93cb74b2d8fe1626c47510958fcb1901e8ceebcebeeb8fb97ff61374e9d1eaec6d07a9828ba9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
